import Link from "next/link";
import React from "react";
import { Metadata } from 'next';
import './about.css';

export const metadata: Metadata = {
  title: 'About | Next App',
  description: 'Generated by create next app',
}

export default function AboutLayout({
    children,
} : {
    children: React.ReactNode;
}){
    return (
        <div className="about column">
            <h1 className="title">About us </h1>
            <ul>
                <li><Link href='/about/contacts'>Contacts</Link></li>
                <li><Link href='/about/team'>Team</Link></li>
            </ul>
            {children}
        </div>
    )
}